### ISSUE TITLE
이미지 스트리밍 질문 있습니다.

### ISSUE THREAD

**Issue by kdi9694** [kbdlab/walking_robot#52]
1. 카메라에서 이미지를 따와 수정 작업을 하는 과정에서 그냥 camera.py에 gaussian blur를 적용시켜도 실행시키면 정상적으로 작동하는데, ImageRW.py에서 작동시키면 다음과 같은 cv2 에러가 발생합니다. 
pi@raspberrypi:~/walking_robot/Networking $ python3 ImageRW.py DESKTOP-R05GSQ5
Connected
Traceback (most recent call last):
  File "ImageRW.py", line 118, in <module>
    main()
  File "ImageRW.py", line 114, in main
    UploadNumpy()
  File "ImageRW.py", line 92, in UploadNumpy
    blur_image = edge_detection(img, thres=thres)
  File "ImageRW.py", line 68, in edge_detection
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) #1. 여기에서 cv2에러가 납니다.
cv2.error: OpenCV(3.4.11) /tmp/pip-wheel-o9sonm06/opencv-python/opencv/modules/imgproc/src/color.simd_helpers.hpp:88: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = (cv::impl::<unnamed>::SizePolicy)2; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

2. gaussian blur 적용 안하고 calibration만 적용하고 돌리면,  연결자체가 안됩니다. 원래 8000포트 쓰다가 자꾸 WSL에서 다음과 같은 오류(1)가 나길래 9091 포트 열어서(방법은 공지사항에 있는 참고영상 7개에 있는 방법으로 했습니다.) 했더니 연결 자체가 안됩니다. 
(1) Traceback (most recent call last):
  File "Server.py", line 65, in <module>
    with socketserver.TCPServer(("0.0.0.0", PORT), Handler) as _httpd:
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

(2)Connected
Traceback (most recent call last):
  File "ImageRW.py", line 118, in <module>
    main()
  File "ImageRW.py", line 114, in main
    UploadNumpy()
  File "ImageRW.py", line 97, in UploadNumpy
    "X-Client2Server" : "123"
  File "ImageRW.py", line 33, in Upload
    conn.request('POST', '/', body=body, headers=headers)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

참고로 키보드 조작은 잘 됩니다.

마지막으로 작성한 코드 올려보겠습니다.
[ImageRW.txt](https://github.com/kbdlab/walking_robot/files/5617719/ImageRW.txt)

**Comment by aegggsehyun1994** [comment]
늦어서 죄송합니다. 도움이 될만한 코드를 올려드리는 데 좀 오래 걸렸습니다. ㅠ
질문을 닫으셔서 찾는 데 한참 걸렸네요 ㅋㅋ
[이겁니다.](https://github.com/kbdlab/walking_robot/blob/master/Networking/KillServer.sh)
